name: space_x_book
description: Test task application for Arch company that contains an overview of SpaceX events and assets
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  #coflicts with dart_code_metrics
  auto_route: 6.4.0
  chopper: 6.1.1
  cached_network_image: 3.2.3
  flutter_bloc: 8.1.2
  get_it: 7.3.0
  intl: 0.18.1
  json_annotation: 4.8.0
  url_launcher: 6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  #coflicts with dart_code_metrics
  auto_route_generator: 6.2.0
  build_runner: 2.3.3
  chopper_generator: 6.0.0
  flutter_gen_runner: ^5.3.0
  dart_code_metrics: 5.7.2
  flutter_lints: 2.0.1
  intl_utils: 2.8.2
  json_serializable: 6.6.1


flutter:
  uses-material-design: true

  assets:
    - assets/images/